version: '2'
services:
    postgres:
        image: 'postgres:10.6'
        container_name: postgres
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: dev_db
        networks:
            - docker_hssm

    grafana:
        build: ./src/grafana
        container_name: grafana
        ports:
            - '3000:3000'
        networks:
            - docker_hssm
        depends_on:
            - postgres

    java:
        build: ./src/java
        container_name: java
        ports:
            - '80:80'
        networks:
            - docker_hssm
        depends_on:
            - postgres

networks:
    docker_hssm:
        driver: bridge