{
 "title": "HSSM - Home",
 "tags": [ "HSSM-Home" ],
 "time": { "from": "now-5y", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "country",
    "label": "Country",
    "query": "select country_code from tweets"
   }
  ]
 },
 "panels": [
  {
   "title": "Hate Speech",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  count(tweet)\nFROM\n  tweets\nWHERE\n  $__timeFilter(created_at)\nand\n  country_code in ($country)"
    }
   ]
  },
  {
   "title": "Hate Speech Map",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 23, "w": 17, "x": 7, "y": 0 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(created_at),\n  count(tweet) as datapoints,\n  country_code as target\nFROM\n  tweets\nWHERE\n  $__timeFilter(created_at)\nand\n  country_code in ($country)\nGROUP BY \n  created_at, country_code"
    }
   ]
  },
  {
   "title": "Hate Speech Details",
   "type": "table",
   "gridPos": { "h": 20, "w": 7, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT\n  *\nFROM \n  tweets\nwhere\n  $__timeFilter(created_at)\nand\n  country_code in ($country)"
    }
   ]
  }
 ]
}